import { defineConfig } from "vite"
import react from "@vitejs/plugin-react-swc"
import typescript from "@rollup/plugin-typescript"

const path = require("path")

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    react({
      jsxImportSource: "@emotion/react",
    }),
  ],
  build: {
    sourcemap: true,
    minify: "esbuild",
    lib: {
      entry: path.resolve(__dirname, "src/index.ts"),
      name: "@flowagent-design/react",
      fileName: (format) => `${format}/index.js`,
    },
    rollupOptions: {
      plugins: [
        typescript({
          tsconfig: path.resolve(__dirname, "tsconfig.json"),
          compilerOptions: {
            rootDir: path.resolve(__dirname, "src"),
            outDir: path.resolve(__dirname, "dist", "types"),
            declaration: true,
          },
          include: path.resolve(__dirname, "src/**"),
          exclude: path.resolve(__dirname, "node_modules/**"),
        }),
      ],
      external: [
        "react",
        "react-dom",
        "@emotion/react",
        "framer-motion",
        "@flowagent-design/system",
        "@flowagent-design/theme",
        "@flowagent-design/config-provider",
        "@flowagent-design/avatar",
        "@flowagent-design/breadcrumb",
        "@flowagent-design/icon",
        "@flowagent-design/image",
        "@flowagent-design/tag",
        "@flowagent-design/divider",
        "@flowagent-design/space",
        "@flowagent-design/button",
        "@flowagent-design/radio",
        "@flowagent-design/typography",
        "@flowagent-design/trigger",
        "@flowagent-design/popover",
        "@flowagent-design/checkbox",
        "@flowagent-design/list",
        "@flowagent-design/link",
        "@flowagent-design/progress",
        "@flowagent-design/empty",
        "@flowagent-design/badge",
        "@flowagent-design/statistic",
        "@flowagent-design/input",
        "@flowagent-design/switch",
        "@flowagent-design/alert",
        "@flowagent-design/input-tag",
        "@flowagent-design/grid",
        "@flowagent-design/popconfirm",
        "@flowagent-design/pagination",
        "@flowagent-design/spin",
        "@flowagent-design/notification",
        "@flowagent-design/input-number",
        "@flowagent-design/message",
        "@flowagent-design/select",
        "@flowagent-design/comment",
        "@flowagent-design/description",
        "@flowagent-design/timeline",
        "@flowagent-design/card",
        "@flowagent-design/rate",
        "@flowagent-design/calendar",
        "@flowagent-design/time-picker",
        "@flowagent-design/modal",
        "@flowagent-design/steps",
        "@flowagent-design/back-top",
        "@flowagent-design/drawer",
        "@flowagent-design/collapse",
        "@flowagent-design/table",
        "@flowagent-design/date-picker",
        "@flowagent-design/result",
        "@flowagent-design/page-header",
        "@flowagent-design/slider",
        "@flowagent-design/menu",
        "@flowagent-design/loading",
        "@flowagent-design/tabs",
        "@flowagent-design/skeleton",
        "@flowagent-design/dropdown",
        "@flowagent-design/affix",
        "@flowagent-design/cascader",
        "@flowagent-design/upload",
      ],
      output: {
        globals: {
          react: "React",
          "react-dom": "ReactDom",
          "@emotion/react": "@emotion/react",
          "framer-motion": "framer-motion",
          "@flowagent-design/system": "@flowagent-design/system",
          "@flowagent-design/theme": "@flowagent-design/theme",
          "@flowagent-design/config-provider":
            "@flowagent-design/config-provider",
          "@flowagent-design/avatar": "@flowagent-design/avatar",
          "@flowagent-design/breadcrumb": "@flowagent-design/breadcrumb",
          "@flowagent-design/icon": "@flowagent-design/icon",
          "@flowagent-design/image": "@flowagent-design/image",
          "@flowagent-design/tag": "@flowagent-design/tag",
          "@flowagent-design/divider": "@flowagent-design/divider",
          "@flowagent-design/space": "@flowagent-design/space",
          "@flowagent-design/button": "@flowagent-design/button",
          "@flowagent-design/radio": "@flowagent-design/radio",
          "@flowagent-design/typography": "@flowagent-design/typography",
          "@flowagent-design/trigger": "@flowagent-design/trigger",
          "@flowagent-design/popover": "@flowagent-design/popover",
          "@flowagent-design/checkbox": "@flowagent-design/checkbox",
          "@flowagent-design/list": "@flowagent-design/list",
          "@flowagent-design/link": "@flowagent-design/link",
          "@flowagent-design/progress": "@flowagent-design/progress",
          "@flowagent-design/empty": "@flowagent-design/empty",
          "@flowagent-design/badge": "@flowagent-design/badge",
          "@flowagent-design/statistic": "@flowagent-design/statistic",
          "@flowagent-design/input": "@flowagent-design/input",
          "@flowagent-design/switch": "@flowagent-design/switch",
          "@flowagent-design/alert": "@flowagent-design/alert",
          "@flowagent-design/input-tag": "@flowagent-design/input-tag",
          "@flowagent-design/grid": "@flowagent-design/grid",
          "@flowagent-design/popconfirm": "@flowagent-design/popconfirm",
          "@flowagent-design/pagination": "@flowagent-design/pagination",
          "@flowagent-design/spin": "@flowagent-design/spin",
          "@flowagent-design/notification": "@flowagent-design/notification",
          "@flowagent-design/input-number": "@flowagent-design/input-number",
          "@flowagent-design/message": "@flowagent-design/message",
          "@flowagent-design/select": "@flowagent-design/select",
          "@flowagent-design/comment": "@flowagent-design/comment",
          "@flowagent-design/description": "@flowagent-design/description",
          "@flowagent-design/timeline": "@flowagent-design/timeline",
          "@flowagent-design/card": "@flowagent-design/card",
          "@flowagent-design/rate": "@flowagent-design/rate",
          "@flowagent-design/calendar": "@flowagent-design/calendar",
          "@flowagent-design/time-picker": "@flowagent-design/time-picker",
          "@flowagent-design/modal": "@flowagent-design/modal",
          "@flowagent-design/steps": "@flowagent-design/steps",
          "@flowagent-design/back-top": "@flowagent-design/back-top",
          "@flowagent-design/drawer": "@flowagent-design/drawer",
          "@flowagent-design/collapse": "@flowagent-design/collapse",
          "@flowagent-design/table": "@flowagent-design/table",
          "@flowagent-design/date-picker": "@flowagent-design/date-picker",
          "@flowagent-design/result": "@flowagent-design/result",
          "@flowagent-design/page-header": "@flowagent-design/page-header",
          "@flowagent-design/slider": "@flowagent-design/slider",
          "@flowagent-design/menu": "@flowagent-design/menu",
          "@flowagent-design/loading": "@flowagent-design/loading",
          "@flowagent-design/tabs": "@flowagent-design/tabs",
          "@flowagent-design/skeleton": "@flowagent-design/skeleton",
          "@flowagent-design/dropdown": "@flowagent-design/dropdown",
          "@flowagent-design/affix": "@flowagent-design/affix",
          "@flowagent-design/cascader": "@flowagent-design/cascader",
          "@flowagent-design/upload": "@flowagent-design/upload",
        },
      },
    },
  },
})
