blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/orgs/khulnasoft-lab/discussions
    about: Ask questions and discuss topics with other community members
  - name: Chat with other community members
    url: https://discord.gg/khulnasoft-lab
    about: The official flowagent Cloud Discord community
