declare namespace NodeJS {
  interface ProcessEnv {
    readonly FLOWAGENT_API_BASE_URL: string
    readonly FLOWAGENT_BUILDER_URL: string
    readonly FLOWAGENT_CLOUD_URL: string
    readonly FLOWAGENT_MARKET_URL: string
    readonly FLOWAGENT_INSTANCE_ID: string
    readonly FLOWAGENT_APP_VERSION: string
    readonly FLOWAGENT_APP_ENV: string
    readonly FLOWAGENT_CLOUD_USER_EMAIL: string
    readonly FLOWAGENT_CLOUD_USER_PASSWORD: string
    readonly FLOWAGENT_CLOUD_TEAM_IDENTITY: string
    readonly FLOWAGENT_SUPABASE_KEY: string
    readonly FLOWAGENT_S3_ACL: string
    readonly FLOWAGENT_S3_REGION: string
    readonly FLOWAGENT_S3_BASEURL: string
    readonly FLOWAGENT_S3_BUCKETNAME: string
    readonly FLOWAGENT_S3_ACCESSKEYID: string
    readonly FLOWAGENT_S3_SECRETACCESSKEY: string
    readonly FLOWAGENT_NEON_HOST: string
    readonly FLOWAGENT_NEON_PORT: string
    readonly FLOWAGENT_NEON_DATABASENAME: string
    readonly FLOWAGENT_NEON_DATABASEPASSWORD: string
    readonly FLOWAGENT_NEON_DATABASEUSERNAME: string
    readonly FLOWAGENT_SMTP_HOST: string
    readonly FLOWAGENT_SMTP_PASSWORD: string
    readonly FLOWAGENT_SMTP_USERNAME: string
    readonly FLOWAGENT_SMTP_PORT: string
    readonly FLOWAGENT_TIDB_HOST: string
    readonly FLOWAGENT_TIDB_PORT: string
    readonly FLOWAGENT_TIDB_DATABASENAME: string
    readonly FLOWAGENT_TIDB_DATABASEPASSWORD: string
    readonly FLOWAGENT_TIDB_DATABASEUSERNAME: string
    readonly FLOWAGENT_MSSQL_HOST: string
    readonly FLOWAGENT_MSSQL_PORT: string
    readonly FLOWAGENT_MSSQL_PASSWORD: string
    readonly FLOWAGENT_MSSQL_USERNAME: string
    readonly FLOWAGENT_MSSQL_DATABASENAME: string
    readonly FLOWAGENT_MYSQL_HOST: string
    readonly FLOWAGENT_MYSQL_PORT: string
    readonly FLOWAGENT_MYSQL_DATABASENAME: string
    readonly FLOWAGENT_MYSQL_DATABASEPASSWORD: string
    readonly FLOWAGENT_MYSQL_DATABASEUSERNAME: string
    readonly FLOWAGENT_REDIS_HOST: string
    readonly FLOWAGENT_REDIS_PORT: string
    readonly FLOWAGENT_REDIS_DATABASEPASSWORD: string
    readonly FLOWAGENT_REDIS_DATABASEUSERNAME: string
    readonly FLOWAGENT_ORACLE_HOST: string
    readonly FLOWAGENT_ORACLE_NAME: string
    readonly FLOWAGENT_ORACLE_PORT: string
    readonly FLOWAGENT_ORACLE_PASSWORD: string
    readonly FLOWAGENT_ORACLE_USERNAME: string
    readonly FLOWAGENT_ORACLE_CONNECTIONTYPE: string
    readonly FLOWAGENT_COUCHDB_HOST: string
    readonly FLOWAGENT_COUCHDB_PORT: string
    readonly FLOWAGENT_COUCHDB_PASSWORD: string
    readonly FLOWAGENT_COUCHDB_USERNAME: string
    readonly FLOWAGENT_MARIADB_HOST: string
    readonly FLOWAGENT_MARIADB_PORT: string
    readonly FLOWAGENT_MARIADB_DATABASENAME: string
    readonly FLOWAGENT_MARIADB_DATABASEPASSWORD: string
    readonly FLOWAGENT_MARIADB_DATABASEUSERNAME: string
    readonly FLOWAGENT_RESTAPI_BASEURL: string
    readonly FLOWAGENT_RESTAPI_AUTHENTICATION: string
    readonly FLOWAGENT_APPWRITE_HOST: string
    readonly FLOWAGENT_APPWRITE_APIKEY: string
    readonly FLOWAGENT_APPWRITE_PROJECTID: string
    readonly FLOWAGENT_APPWRITE_DATABASEID: string
    readonly FLOWAGENT_FIREBASE_PROJECTID: string
    readonly FLOWAGENT_FIREBASE_DATABASEURL: string
    readonly FLOWAGENT_FIREBASE_PRIVATEKEY: string
    readonly FLOWAGENT_POSTGRESQL_HOST: string
    readonly FLOWAGENT_POSTGRESQL_PORT: string
    readonly FLOWAGENT_POSTGRESQL_DATABASENAME: string
    readonly FLOWAGENT_POSTGRESQL_DATABASEPASSWORD: string
    readonly FLOWAGENT_POSTGRESQL_DATABASEUSERNAME: string
    readonly FLOWAGENT_HUGGINGFACE_TOKEN: string
    readonly FLOWAGENT_GOOGLESHEETS_AUTHENTICATION: string
    readonly FLOWAGENT_GOOGLESHEETS_PRIVATEKEY: string
    readonly FLOWAGENT_ELASTICSEARCH_HOST: string
    readonly FLOWAGENT_ELASTICSEARCH_PORT: string
    readonly FLOWAGENT_ELASTICSEARCH_PASSWORD: string
    readonly FLOWAGENT_ELASTICSEARCH_USERNAME: string
  }
}
